apiVersion: v1
kind: PersistentVolume
metadata:
  name: world-backup
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/vincent/minecraft-automation/backups/worldname
  claimRef:
    name: backup-world-claim
    namespace: worldnamespace
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dalek
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-world-claim
  namespace: worldnamespace
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: world-backup
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
