apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
  namespace: worldnamespace
spec:
  schedule: "35 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: worldclaim
            persistentVolumeClaim:
              claimName: worldclaim
          - name: backup-world-claim
            persistentVolumeClaim:
              claimName: backup-world-claim

          containers:
          - name: worldbackup
            image: localhost:32000/backup:latest
            env:
            - name: WORLD_NAME
              value: "worldname"
            - name: MCRCON_HOST
              value: "minecraft-rcon"
            - name: MCRCON_PASS
              valueFrom:
                secretKeyRef:
                  name: rcon-secrets
                  key: rconpass
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: bucket
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: endpoint
            - name: KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: id
            - name: KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: secret
                  
            volumeMounts:
            - name: worldclaim
              mountPath: /home/server/data
            - name: backup-world-claim
              mountPath: /home/server/backups
          restartPolicy: OnFailure
