apiVersion: v1
kind: Service
metadata:
  name: minecraft-management
  namespace: worldnamespace

spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000

  selector:
    app: minecraft-management

  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: management
  namespace: worldnamespace

spec:
  entryPoints:
    - web

  routes:
    - match: PathPrefix(`/`)
      kind: Rule

      services:
        - name: minecraft-management
          port: 3000