apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: worldnamespace
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  namespace: worldnamespace
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25575
    targetPort: 25575
  