apiVersion: v1
kind: PersistentVolume
metadata:
  name: worldname
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/vincent/minecraft-automation/worlds
  claimRef:
    name: worldclaim
    namespace: worldnamespace
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dalek