apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worldclaim
  namespace: worldnamespace
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: worldname
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
