---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-volume
spec:
  capacity:
    storage: {{ .Values.storage.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cert-local-storage
  local:
    path:  {{ .Values.storage.certDir }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.hostname }}