apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.worldName }}-bluemap-volume-config
spec:
  capacity:
    storage: "100M"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.worldName }}-local-storage
  local:
    path: {{ .Values.storage.worldDir }}/bluemap-config/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.hostname }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.worldName }}-bluemap-volume-data
spec:
  capacity:
    storage: {{ .Values.storage.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.worldName }}-local-storage
  local:
    path:  {{ .Values.storage.worldDir }}/bluemap-config/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.hostname }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.worldName }}-bluemap-volume-web
spec:
  capacity:
    storage: "100M"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.worldName }}-local-storage
  local:
    path:  {{ .Values.storage.worldDir }}/bluemap-config/web
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.hostname }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-config-claim
spec:
  resources:
    requests:
      storage: "100M"
  storageClassName: {{ .Values.worldName }}-local-storage
  volumeName: {{ .Values.worldName }}-bluemap-volume-config
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-data-claim
spec:
  resources:
    requests:
      storage: {{ .Values.storage.volumeSize }}
  storageClassName: {{ .Values.worldName }}-local-storage
  volumeName: {{ .Values.worldName }}-bluemap-volume-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-web-claim
spec:
  resources:
    requests:
      storage: "100M"
  storageClassName: {{ .Values.worldName }}-local-storage
  volumeName: {{ .Values.worldName }}-bluemap-volume-web
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
