apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluemap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluemap
  
  template:
    metadata:
      labels:
        app: bluemap

    spec:
      volumes:
      - name: worldclaim
        persistentVolumeClaim:
          claimName: {{ .Values.worldName }}-claim
      - name: bluemap-config-claim
        persistentVolumeClaim:
          claimName: bluemap-config-claim
      - name: bluemap-web-claim
        persistentVolumeClaim:
          claimName: bluemap-web-claim
      - name: bluemap-data-claim
        persistentVolumeClaim:
          claimName: bluemap-data-claim
      
      initContainers:
      - name: bluemap-setup
        image: ghcr.io/bluemap-minecraft/bluemap:v4.1
        resources:
          limits:
            ephemeral-storage: 1Gi
        volumeMounts:
          - name: bluemap-config-claim
            mountPath: /app/config
        command: ["sh", "-c", "java -jar cli.jar; echo done"]

      - name: busybox-accept-download
        image: busybox:1.28
        resources:
          limits:
            ephemeral-storage: 1Gi
        volumeMounts:
          - name: bluemap-config-claim
            mountPath: /app/config
        command: ['sh', '-c', "sed -i 's/accept-download:.*/accept-download: true/' /app/config/core.conf"]

      containers:
      - name: bluemap
        image: ghcr.io/bluemap-minecraft/bluemap:v4.1
        resources:
          limits:
            ephemeral-storage: 1Gi
        volumeMounts:
          - name: bluemap-config-claim
            mountPath: /app/config
          - name: bluemap-data-claim
            mountPath: /app/data
          - name: bluemap-web-claim
            mountPath: /app/web
          - name: worldclaim
            mountPath: /app/world
            subPath: world
        ports:
          - containerPort: 8100
        args: ["-r", "-u", "-w"]
