apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-management
  
  template:
    metadata:
      labels:
        app: minecraft-management

    spec:
      volumes:
      - name: worldclaim
        persistentVolumeClaim:
          claimName: {{ .Values.worldName }}-claim
      - name: bluemap-config-claim
        persistentVolumeClaim:
          claimName: bluemap-config-claim
      - name: bluemap-data-claim
        persistentVolumeClaim:
          claimName: bluemap-data-claim
      - name: bluemap-web-claim
        persistentVolumeClaim:
          claimName: bluemap-web-claim

      containers:
      - name: management
        image: localhost:32000/management:latest
        resources:
          limits:
            ephemeral-storage: 1Gi
        volumeMounts:
          - name: worldclaim
            mountPath: /home/workspace/world-data
          - name: bluemap-config-claim
            mountPath: /home/workspace/bluemap-config
          - name: bluemap-data-claim
            mountPath: /home/workspace/bluemap-data
          - name: bluemap-web-claim
            mountPath: /home/workspace/bluemap-web

        env:
          - name: MCRCON_HOST
            value: "minecraft-rcon"
          - name: MCRCON_PASS
            valueFrom:
              secretKeyRef:
                name: rcon-secrets
                key: rconpass
        ports:
          - containerPort: 3000