apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    nodePort: {{ .Values.ingress.minecraft.nodePort }}
  - name: voicechat
    port: 24454
    targetPort: 24454
    nodePort: {{ .Values.ingress.minecraft.voiceChatNodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25575
    targetPort: 25575
  