apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
type: Opaque
stringData:
  id: {{ .Values.secrets.s3Id }}
  secret: {{ .Values.secrets.s3Secret }}
  endpoint: {{ .Values.secrets.s3Endpoint }}
  bucket: {{ .Values.secrets.s3Bucket }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rcon-secrets
type: Opaque
stringData:
  rconpass: {{ .Values.secrets.rconPass }}
