apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-config-claim
  namespace: worldnamespace
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: bluemap-volume-config
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-data-claim
  namespace: worldnamespace
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: bluemap-volume-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-web-claim
  namespace: worldnamespace
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: bluemap-volume-web
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
