---
- name: Setup backup cron job
  hosts: localhost
  tasks:

  - name: Deletes a backup cron job
    ansible.builtin.cron:
      name: "Run backup {{ world }} container"
      state: absent

  - name: Deletes a cleanup cron job
    ansible.builtin.cron:
      name: "Run cleanup {{ world }} container"
      state: absent
